### ISSUE TITLE
player_wall_stoppers doesn't work against certain angles.

### ISSUE THREAD

**Issue by TsukiruP** [DarkD04/Harmony-Framework#2]
When you have expertly crafted level design like this:
![image](https://github.com/DarkD04/Harmony-Framework/assets/104665617/e32e65b5-e530-4f4c-8b9b-0d3b70e8a595)

The player doesn't immediately stop, and has to wait on friction to make them dethatch from the wall.

This is because the script only checks for x_speed and not ground_speed:
![image](https://github.com/DarkD04/Harmony-Framework/assets/104665617/9e75d561-c07c-4940-9675-5bde2ad1f104)

If you swap x_speed with ground_speed, the player immediately stops and drops. Though ideally you'd want both x_speed and ground_speed checked.

P.S: "jump_strenght" is a typo that's all over the engine.

**Comment by TsukiruP** [comment]
#3 Put out a pull request just doing it myself.

**Comment by DarkD04** [comment]
This has been fixed in Aural and Legends but hasn't been ported in public yet considering im going to be rewritting some code once i have time

**Comment by TsukiruP** [comment]
Ah alright then. I'll wait on that then before doing anything else.
